[platformio]
default_envs = wt32-eth01
src_dir = .

[env:wt32-eth01]
platform = espressif32 @ ~6.5.0
board = wt32-eth01
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.partitions = default.csv

lib_deps =
    knolleary/PubSubClient @ ^2.8
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^6.21.4

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DMQTT_MAX_PACKET_SIZE=1024
